### ISSUE TITLE
Remove `_tokenCount` constructor param for CurvelikeAdapter and save token index

### ISSUE THREAD

**Issue by halo3mic** [yieldyak/yak-aggregator#30]
## About

Instead of the deployer having to specify the number of tokens that the Curvelike pool uses this could be done during contract deployment by looping through indices until an error is caught. Additionally, during the deployment map of indices for tokens could be saved. This would avoid the cost of calls `getTokenIndex` to the pool.

An implementation for this can be found in `SynapseAdapter`
https://github.com/yieldyak/yak-aggregator/blob/0595b66bc6fc1695641f7ef2162e6ce24b666ef1/contracts/adapters/SynapseAdapter.sol#L47-L62

## TODO

 - [ ] Implementation in Curvelike smart contract
 - [ ] Replace `getTokenIndex` calls with mapping lookup (in Curvelike smart contract)
 - [ ] Remove `_tokenCount` param in fixtures
 - [ ] Remove `_tokenCount` param in tests
